added layout, hovers
ArturNagaycev/tailwind_inteo_layout pull request #1
Opened 2023-03-17 14:50 UTC by ArturNagaycev

[DEMO](https://tailwind-inteo-layout.vercel.app/)

2023-03-21 18:55 UTC, dmytro-mashchenko commented on dist/index.html
> +      </section>
I am not sure, but this button make a unnecessary gap between main image in this section and awards section. I saw your demo in vercel.

2023-03-21 18:55 UTC, dmytro-mashchenko commented on dist/index.html
> +          </button>
This button a bit large in the mockup

2023-03-22 08:03 UTC, dima0208 approved these changes

2023-03-30 18:07 UTC, IgorNovikov10 requested changes

2023-03-30 18:07 UTC, IgorNovikov10 commented on dist/index.html
> +              <h4 class="pretitle mb-0">
consider not to use headings for this type of text ABOUT US as it's more descriptive text for the user, SEO-related heading here will be <h2 class="heading">

2023-04-20 11:02 UTC, merged